import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Plus, Save } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { createLeadSource, createProduct, createProductVariant, getAdminMasterConfig, updateCareRule, updateLeadSource, updatePipelineStage, updateProduct, updateProductVariant } from '../lib/api'
import { Button, Card, EmptyState, Skeleton } from './UI'
import { Sheet } from './Sheet'

const slug=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'')
const potential=(x:string)=>x==='hot'?'Nóng':x==='potential'?'Tiềm năng':'Theo dõi'

export function AdminMasterConfig(){
  const q=useQuery({queryKey:['admin-master-config'],queryFn:getAdminMasterConfig});const qc=useQueryClient();const[busy,setBusy]=useState('');const[err,setErr]=useState('');const[newSource,setNewSource]=useState(false);const[newProduct,setNewProduct]=useState(false);const[variantProduct,setVariantProduct]=useState<any|null>(null)
  const refresh=()=>qc.invalidateQueries({queryKey:['admin-master-config']})
  const run=async(key:string,fn:()=>Promise<any>)=>{setBusy(key);setErr('');try{await fn();await refresh();return true}catch(e:any){setErr(e.message||'Không thể lưu cấu hình');return false}finally{setBusy('')}}
  if(q.isLoading)return <Skeleton lines={8}/>
  if(q.isError)return <EmptyState title="Không tải được cấu hình" description={q.error.message} action={<Button onClick={()=>q.refetch()}>Thử lại</Button>}/>
  const d:any=q.data
  return <div className="master-config">{err&&<div className="form-error">{err}</div>}
    <section><div className="section-title"><h2>Nguồn khách</h2><Button variant="secondary" onClick={()=>setNewSource(true)}><Plus className="h-4 w-4" strokeWidth={1.75}/> Thêm nguồn</Button></div><div className="config-list">{d?.sources.map((x:any)=><SourceRow key={x.id} x={x} busy={busy===x.id} save={(patch:any)=>run(x.id,()=>updateLeadSource(x.id,patch))}/>)}</div></section>
    <section><div className="section-title"><h2>Phễu bán hàng</h2><span>Code hệ thống được giữ cố định</span></div><div className="config-list">{d?.stages.map((x:any)=><StageRow key={x.id} x={x} busy={busy===x.id} save={(patch:any)=>run(x.id,()=>updatePipelineStage(x.id,patch))}/>)}</div></section>
    <section><div className="section-title"><h2>Danh mục xe</h2><Button variant="secondary" onClick={()=>setNewProduct(true)}><Plus className="h-4 w-4" strokeWidth={1.75}/> Thêm dòng xe</Button></div><div className="config-list">{d?.products.map((x:any)=><ProductRow key={x.id} x={x} busy={busy.startsWith(x.id)} run={run} addVariant={()=>setVariantProduct(x)}/>)}</div></section>
    <section><div className="section-title"><h2>Quy tắc chăm sóc</h2><span>Thời gian tối đa chưa có tương tác</span></div><div className="config-list">{d?.careRules.map((x:any)=><CareRow key={x.id} x={x} busy={busy===x.id} save={(patch:any)=>run(x.id,()=>updateCareRule(x.id,patch))}/>)}</div></section>
    <NewSourceSheet open={newSource} onClose={()=>setNewSource(false)} nextSort={Math.max(0,...(d?.sources??[]).map((x:any)=>x.sort_order||0))+10} save={async v=>{const ok=await run('new-source',()=>createLeadSource(v));if(ok)setNewSource(false)}} busy={busy==='new-source'}/>
    <NewProductSheet open={newProduct} onClose={()=>setNewProduct(false)} nextSort={Math.max(0,...(d?.products??[]).map((x:any)=>x.sort_order||0))+10} save={async v=>{const ok=await run('new-product',()=>createProduct(v));if(ok)setNewProduct(false)}} busy={busy==='new-product'}/>
    <NewVariantSheet product={variantProduct} onClose={()=>setVariantProduct(null)} save={async v=>{if(!variantProduct)return;const ok=await run(`${variantProduct.id}-new`,()=>createProductVariant({productId:variantProduct.id,...v}));if(ok)setVariantProduct(null)}} busy={!!variantProduct&&busy===`${variantProduct.id}-new`}/>
  </div>
}
function NewSourceSheet({open,onClose,nextSort,save,busy}:{open:boolean;onClose:()=>void;nextSort:number;save:(v:any)=>void;busy:boolean}){const[name,setName]=useState('');const[priority,setPriority]=useState(true);const[sla,setSla]=useState('15');const[sort,setSort]=useState(nextSort);return <Sheet open={open} onClose={onClose} title="Thêm nguồn khách"><div className="form-stack"><label>Tên nguồn *<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ví dụ: Facebook Ads"/></label><label>Thứ tự<input type="number" value={sort} onChange={e=>setSort(+e.target.value)}/></label><label>SLA phản hồi (phút)<input type="number" value={sla} onChange={e=>setSla(e.target.value)}/></label><label className="checkline"><input type="checkbox" checked={priority} onChange={e=>setPriority(e.target.checked)}/> Nguồn ưu tiên / trả phí</label><Button disabled={busy||!name.trim()} onClick={()=>save({name:name.trim(),code:slug(name),sort_order:sort,is_priority:priority,response_sla_minutes:sla?+sla:null})}>{busy?'Đang lưu...':'Thêm nguồn'}</Button></div></Sheet>}
function NewProductSheet({open,onClose,nextSort,save,busy}:{open:boolean;onClose:()=>void;nextSort:number;save:(v:any)=>void;busy:boolean}){const[name,setName]=useState('');const[brand,setBrand]=useState('MG');const[sort,setSort]=useState(nextSort);return <Sheet open={open} onClose={onClose} title="Thêm dòng xe"><div className="form-stack"><label>Hãng<input value={brand} onChange={e=>setBrand(e.target.value)}/></label><label>Dòng xe *<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ví dụ: MG7"/></label><label>Thứ tự<input type="number" value={sort} onChange={e=>setSort(+e.target.value)}/></label><Button disabled={busy||!name.trim()} onClick={()=>save({name:name.trim(),brand:brand.trim()||'MG',code:slug(name).toUpperCase(),sort_order:sort})}>{busy?'Đang lưu...':'Thêm dòng xe'}</Button></div></Sheet>}
function NewVariantSheet({product,onClose,save,busy}:{product:any|null;onClose:()=>void;save:(v:any)=>void;busy:boolean}){const[name,setName]=useState('');const[price,setPrice]=useState('');useEffect(()=>{if(product){setName('');setPrice('')}},[product?.id]);const nextSort=useMemo(()=>Math.max(0,...(product?.product_variants??[]).map((v:any)=>v.sort_order||0))+10,[product]);return <Sheet open={!!product} onClose={onClose} title={`Thêm phiên bản${product?` · ${product.name}`:''}`}><div className="form-stack"><label>Tên phiên bản *<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ví dụ: Luxury"/></label><label>Giá niêm yết<input type="number" value={price} onChange={e=>setPrice(e.target.value)} placeholder="Không bắt buộc"/></label><Button disabled={busy||!name.trim()} onClick={()=>save({name:name.trim(),code:slug(name).toUpperCase(),listPrice:price?+price:null,sortOrder:nextSort})}>{busy?'Đang lưu...':'Thêm phiên bản'}</Button></div></Sheet>}
function SourceRow({x,save,busy}:{x:any;save:(p:any)=>void;busy:boolean}){const[name,setName]=useState(x.name);const[sort,setSort]=useState(x.sort_order);const[sla,setSla]=useState(x.response_sla_minutes??'');const[priority,setPriority]=useState(x.is_priority);const[active,setActive]=useState(x.is_active);return <Card className="config-row"><div><small>{x.code}</small><input value={name} onChange={e=>setName(e.target.value)}/></div><label>Thứ tự<input type="number" value={sort} onChange={e=>setSort(+e.target.value)}/></label><label>SLA phút<input type="number" value={sla} onChange={e=>setSla(e.target.value===''?'':+e.target.value)}/></label><label className="checkline"><input type="checkbox" checked={priority} onChange={e=>setPriority(e.target.checked)}/> Ưu tiên</label><label className="checkline"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Hiện</label><Button variant="secondary" disabled={busy} onClick={()=>save({name,sort_order:sort,response_sla_minutes:sla===''?null:sla,is_priority:priority,is_active:active})}><Save className="h-4 w-4" strokeWidth={1.75}/> Lưu</Button></Card>}
function StageRow({x,save,busy}:{x:any;save:(p:any)=>void;busy:boolean}){const[name,setName]=useState(x.display_name);const[sort,setSort]=useState(x.sort_order);const[active,setActive]=useState(x.is_active);return <Card className="config-row simple"><div><small>{x.code}</small><input value={name} onChange={e=>setName(e.target.value)}/></div><label>Thứ tự<input type="number" value={sort} onChange={e=>setSort(+e.target.value)}/></label><label className="checkline"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Hiện</label><Button variant="secondary" disabled={busy} onClick={()=>save({display_name:name,sort_order:sort,is_active:active})}><Save className="h-4 w-4" strokeWidth={1.75}/> Lưu</Button></Card>}
function ProductRow({x,run,busy,addVariant}:{x:any;run:(key:string,fn:()=>Promise<any>)=>void;busy:boolean;addVariant:()=>void}){const[name,setName]=useState(x.name);const[sort,setSort]=useState(x.sort_order);const[active,setActive]=useState(x.is_active);return <Card className="product-config"><div className="config-row-head"><div><small>{x.code}</small><input value={name} onChange={e=>setName(e.target.value)}/></div><label>Thứ tự<input type="number" value={sort} onChange={e=>setSort(+e.target.value)}/></label><label className="checkline"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Hiện</label><Button variant="secondary" disabled={busy} onClick={()=>run(x.id,()=>updateProduct(x.id,{name,sort_order:sort,is_active:active}))}><Save className="h-4 w-4" strokeWidth={1.75}/> Lưu</Button></div><div className="variant-list">{(x.product_variants??[]).map((v:any)=><VariantRow key={v.id} v={v} run={run}/>)}<button className="add-inline" onClick={addVariant}><Plus className="h-4 w-4" strokeWidth={1.75}/> Thêm phiên bản</button></div></Card>}
function VariantRow({v,run}:{v:any;run:(key:string,fn:()=>Promise<any>)=>void}){const[name,setName]=useState(v.name);const[price,setPrice]=useState(v.list_price??'');const[active,setActive]=useState(v.is_active);return <div className="variant-row"><input value={name} onChange={e=>setName(e.target.value)}/><input aria-label="Giá niêm yết" type="number" value={price} placeholder="Giá niêm yết" onChange={e=>setPrice(e.target.value===''?'':+e.target.value)}/><label className="checkline"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Hiện</label><button className="icon-btn" onClick={()=>run(v.id,()=>updateProductVariant(v.id,{name,list_price:price===''?null:price,is_active:active}))}><Save className="h-4 w-4" strokeWidth={1.75}/></button></div>}
function CareRow({x,save,busy}:{x:any;save:(p:any)=>void;busy:boolean}){const[hours,setHours]=useState(x.max_inactive_hours);const[active,setActive]=useState(x.is_active);return <Card className="config-row care"><strong>{potential(x.potential_level)}</strong><label>Số giờ<input type="number" value={hours} onChange={e=>setHours(+e.target.value)}/></label><label className="checkline"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Hoạt động</label><Button variant="secondary" disabled={busy} onClick={()=>save({max_inactive_hours:hours,is_active:active})}><Save className="h-4 w-4" strokeWidth={1.75}/> Lưu</Button></Card>}
