import { useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { addCustomerContact, createOpportunity, getMasterData } from '../lib/api'
import { Button } from './UI'
import { Sheet } from './Sheet'

export function AddContactSheet({open,onClose,customerId}:{open:boolean;onClose:()=>void;customerId:string}){
 const[type,setType]=useState('phone');const[value,setValue]=useState('');const[primary,setPrimary]=useState(false);const[busy,setBusy]=useState(false);const[err,setErr]=useState('');const qc=useQueryClient();const save=async()=>{if(!value.trim())return;setBusy(true);setErr('');try{await addCustomerContact({customerId,contactType:type,rawValue:value,isPrimary:primary});await qc.invalidateQueries({queryKey:['customer',customerId]});onClose();setValue('')}catch(e){setErr(e instanceof Error?e.message:'Không thể thêm liên hệ')}finally{setBusy(false)}};return <Sheet open={open} onClose={onClose} title="Thêm liên hệ"><div className="form-stack"><label>Loại<select value={type} onChange={e=>setType(e.target.value)}><option value="phone">Số điện thoại</option><option value="facebook">Facebook</option><option value="messenger">Messenger</option><option value="tiktok">TikTok</option><option value="zalo">Zalo</option><option value="email">Email</option><option value="other">Khác</option></select></label><label>Thông tin<input value={value} onChange={e=>setValue(e.target.value)} autoFocus/></label><label className="checkline"><input type="checkbox" checked={primary} onChange={e=>setPrimary(e.target.checked)}/><span>Đặt làm liên hệ chính</span></label>{err&&<div className="form-error">{err}</div>}<Button disabled={busy||!value.trim()} onClick={save}>{busy?'Đang lưu...':'Thêm liên hệ'}</Button></div></Sheet>
}

export function NewOpportunitySheet({open,onClose,customerId}:{open:boolean;onClose:()=>void;customerId:string}){
 const q=useQuery({queryKey:['master'],queryFn:getMasterData,enabled:open});const[product,setProduct]=useState('');const[busy,setBusy]=useState(false);const[err,setErr]=useState('');const qc=useQueryClient();const save=async()=>{setBusy(true);setErr('');try{await createOpportunity({customerId,productId:product||undefined});await qc.invalidateQueries({queryKey:['customer',customerId]});onClose();setProduct('')}catch(e){setErr(e instanceof Error?e.message:'Không thể tạo cơ hội')}finally{setBusy(false)}};return <Sheet open={open} onClose={onClose} title="Cơ hội bán hàng mới"><div className="form-stack"><label>Xe quan tâm<select value={product} onChange={e=>setProduct(e.target.value)}><option value="">Chưa xác định</option>{q.data?.products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><p className="form-hint">Cơ hội mới sẽ bắt đầu ở giai đoạn “Khách mới”.</p>{q.isError&&<div className="form-error">{q.error.message}</div>}{err&&<div className="form-error">{err}</div>}<Button disabled={busy||q.isError} onClick={save}>{busy?'Đang tạo...':'Tạo cơ hội'}</Button></div></Sheet>
}
