import { useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import type { OpportunityCard } from '../lib/types'
import { changeOpportunityStage, getLostReasons, getMasterData, markLost, markWon, pauseOpportunity, updateOpportunity } from '../lib/api'
import { Button } from './UI'
import { Sheet } from './Sheet'

export function OpportunityEditSheet({open,onClose,opportunity}:{open:boolean;onClose:()=>void;opportunity:OpportunityCard}){
 const[priority,setPriority]=useState(opportunity.priority);const[timeline,setTimeline]=useState(opportunity.purchase_timeline);const[payment,setPayment]=useState(opportunity.payment_type);const[loan,setLoan]=useState(opportunity.loan_ratio?.toString()??'');const[min,setMin]=useState(opportunity.budget_min?.toString()??'');const[max,setMax]=useState(opportunity.budget_max?.toString()??'');const[competitor,setCompetitor]=useState(opportunity.competitor_note??'');const[busy,setBusy]=useState(false);const[err,setErr]=useState('');const qc=useQueryClient()
 const save=async()=>{setBusy(true);setErr('');try{await updateOpportunity(opportunity.id,{priority,purchase_timeline:timeline,payment_type:payment,loan_ratio:payment==='loan'&&loan?Number(loan):null,budget_min:min?Number(min):null,budget_max:max?Number(max):null,competitor_note:competitor||null});await qc.invalidateQueries({queryKey:['customer']});onClose()}catch(e){setErr(e instanceof Error?e.message:'Không thể cập nhật nhu cầu')}finally{setBusy(false)}}
 return <Sheet open={open} onClose={onClose} title="Cập nhật nhu cầu"><div className="form-stack"><fieldset><legend>Mức ưu tiên</legend><div className="choice-grid"><button type="button" className={priority==='normal'?'selected':''} onClick={()=>setPriority('normal')}>Bình thường</button><button type="button" className={priority==='high'?'selected':''} onClick={()=>setPriority('high')}>Cao</button></div></fieldset><label>Dự kiến mua<select value={timeline} onChange={e=>setTimeline(e.target.value)}><option value="now">Ngay</option><option value="within_7_days">Trong 7 ngày</option><option value="within_month">Trong tháng</option><option value="one_to_three_months">1–3 tháng</option><option value="over_three_months">Trên 3 tháng</option><option value="unknown">Chưa xác định</option></select></label><label>Thanh toán<select value={payment} onChange={e=>setPayment(e.target.value)}><option value="cash">Tiền mặt</option><option value="loan">Vay ngân hàng</option><option value="unknown">Chưa xác định</option></select></label>{payment==='loan'&&<label>Tỷ lệ vay (%)<input type="number" min="0" max="100" value={loan} onChange={e=>setLoan(e.target.value)}/></label>}<div className="two-col"><label>Ngân sách từ<input type="number" value={min} onChange={e=>setMin(e.target.value)} placeholder="700000000"/></label><label>Đến<input type="number" value={max} onChange={e=>setMax(e.target.value)} placeholder="750000000"/></label></div><label>Đối thủ đang cân nhắc<input value={competitor} onChange={e=>setCompetitor(e.target.value)} placeholder="Ví dụ: Toyota Camry"/></label>{err&&<div className="form-error">{err}</div>}<Button disabled={busy} onClick={save}>{busy?'Đang lưu...':'Lưu thay đổi'}</Button></div></Sheet>
}

export function StageSheet({open,onClose,opportunityId,currentStageId}:{open:boolean;onClose:()=>void;opportunityId:string;currentStageId?:string}){const q=useQuery({queryKey:['master'],queryFn:getMasterData,enabled:open});const[busy,setBusy]=useState('');const[err,setErr]=useState('');const qc=useQueryClient();const select=async(id:string)=>{setBusy(id);setErr('');try{await changeOpportunityStage(opportunityId,id);await Promise.all([qc.invalidateQueries({queryKey:['customer']}),qc.invalidateQueries({queryKey:['pipeline']})]);onClose()}catch(e){setErr(e instanceof Error?e.message:'Không thể đổi giai đoạn')}finally{setBusy('')}};return <Sheet open={open} onClose={onClose} title="Chọn giai đoạn">{err&&<div className="form-error">{err}</div>}{q.isError&&<div className="form-error">{q.error.message}</div>}<div className="option-list">{q.data?.stages.map(s=><button key={s.id} className={s.id===currentStageId?'selected':''} disabled={!!busy} onClick={()=>select(s.id)}><span>{s.display_name}</span>{s.id===currentStageId&&<b>Hiện tại</b>}</button>)}</div></Sheet>}

export function OpportunityCloseSheet({open,onClose,opportunityId}:{open:boolean;onClose:()=>void;opportunityId:string}){const[mode,setMode]=useState<'pause'|'won'|'lost'>('pause');const[note,setNote]=useState('');const[days,setDays]=useState('30');const[price,setPrice]=useState('');const[reason,setReason]=useState('');const reasons=useQuery({queryKey:['lost-reasons'],queryFn:getLostReasons,enabled:open&&mode==='lost'});const[busy,setBusy]=useState(false);const[err,setErr]=useState('');const qc=useQueryClient();const save=async()=>{setBusy(true);setErr('');try{if(mode==='pause'){const d=new Date();d.setDate(d.getDate()+Number(days));d.setHours(9,0,0,0);await pauseOpportunity(opportunityId,d.toISOString(),note)}else if(mode==='won'){await markWon(opportunityId,price?Number(price):undefined,note)}else{if(!reason)throw new Error('Vui lòng chọn lý do');await markLost(opportunityId,reason,note)}await Promise.all([qc.invalidateQueries({queryKey:['customer']}),qc.invalidateQueries({queryKey:['pipeline']}),qc.invalidateQueries({queryKey:['today']})]);onClose()}catch(e){setErr(e instanceof Error?e.message:'Không thể đổi trạng thái')}finally{setBusy(false)}};return <Sheet open={open} onClose={onClose} title="Trạng thái cơ hội"><div className="form-stack"><div className="segmented three"><button className={mode==='pause'?'active':''} onClick={()=>setMode('pause')}>Tạm hoãn</button><button className={mode==='won'?'active':''} onClick={()=>setMode('won')}>Thành công</button><button className={mode==='lost'?'active':''} onClick={()=>setMode('lost')}>Không thành công</button></div>{mode==='pause'&&<label>Chăm lại sau<select value={days} onChange={e=>setDays(e.target.value)}><option value="30">30 ngày</option><option value="60">60 ngày</option><option value="90">90 ngày</option></select></label>}{mode==='won'&&<label>Giá chốt (không bắt buộc)<input type="number" value={price} onChange={e=>setPrice(e.target.value)}/></label>}{mode==='lost'&&<label>Lý do *<select value={reason} onChange={e=>setReason(e.target.value)}><option value="">Chọn lý do</option>{reasons.data?.map((r:any)=><option key={r.id} value={r.id}>{r.display_name}</option>)}</select></label>}<label>Ghi chú<textarea rows={3} value={note} onChange={e=>setNote(e.target.value)}/></label>{err&&<div className="form-error">{err}</div>}{reasons.isError&&mode==='lost'&&<div className="form-error">{reasons.error.message}</div>}<Button disabled={busy||(mode==='lost'&&!reason)} onClick={save}>{busy?'Đang lưu...':'Xác nhận'}</Button></div></Sheet>}
