import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Lock, Plus, ShieldCheck, Unlock, UsersRound } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Sheet } from '../components/Sheet'
import { Badge, Button, Card, EmptyState, PageTitle, Skeleton } from '../components/UI'
import { adminCreateUser, adminLockUser, adminUpdateUser, getAdminUsers, getOrgStructure } from '../lib/api'
import { roleLabel } from '../lib/format'
import { AdminMasterConfig } from '../components/AdminMasterConfig'

function UserForm({open,onClose,user}:{open:boolean;onClose:()=>void;user?:any}){
  const structure=useQuery({queryKey:['org-structure'],queryFn:getOrgStructure,enabled:open})
  const[email,setEmail]=useState('');const[name,setName]=useState(user?.full_name??'');const[role,setRole]=useState(user?.role??'sales');const[dept,setDept]=useState(user?.department_id??'');const[team,setTeam]=useState(user?.team_id??'');const[busy,setBusy]=useState(false);const[err,setErr]=useState('');const qc=useQueryClient()
  useEffect(()=>{if(open){setEmail('');setName(user?.full_name??'');setRole(user?.role??'sales');setDept(user?.department_id??'');setTeam(user?.team_id??'');setErr('')}},[open,user?.id])
  const teams=(structure.data?.teams??[]).filter((t:any)=>!dept||t.department_id===dept)
  const valid=!!name.trim()&&(!!user||!!email.trim())&&(role==='admin'||!!dept)&&(!['sales','team_leader'].includes(role)||!!team)
  const save=async()=>{if(!valid)return;setBusy(true);setErr('');try{if(user){await adminUpdateUser({user_id:user.id,full_name:name.trim(),role,department_id:role==='admin'?null:dept||null,team_id:['sales','team_leader'].includes(role)?team||null:null})}else{await adminCreateUser({email:email.trim(),full_name:name.trim(),role,department_id:role==='admin'?null:dept||null,team_id:['sales','team_leader'].includes(role)?team||null:null})}await qc.invalidateQueries({queryKey:['admin-users']});onClose()}catch(e:any){setErr(e.message||'Không thể lưu tài khoản')}finally{setBusy(false)}}
  return <Sheet open={open} onClose={onClose} title={user?'Chỉnh tài khoản':'Tạo tài khoản'}><div className="form-stack">{!user&&<label>Email *<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>}<label>Họ tên *<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Vai trò<select value={role} onChange={e=>{setRole(e.target.value);setTeam('')}}><option value="sales">Nhân viên bán hàng</option><option value="team_leader">Trưởng nhóm bán hàng</option><option value="sales_manager">Trưởng phòng bán hàng</option><option value="admin">Quản trị viên</option></select></label>{role!=='admin'&&<label>Phòng<select value={dept} onChange={e=>{setDept(e.target.value);setTeam('')}}><option value="">Chọn phòng</option>{structure.data?.departments.map((d:any)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>}{['sales','team_leader'].includes(role)&&<label>Nhóm<select value={team} onChange={e=>setTeam(e.target.value)}><option value="">Chọn nhóm</option>{teams.map((t:any)=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}{structure.isError&&<div className="form-error">Không tải được phòng/nhóm: {structure.error.message}</div>}{err&&<div className="form-error">{err}</div>}<Button disabled={busy||!valid||structure.isError} onClick={save}>{busy?'Đang lưu...':user?'Lưu thay đổi':'Tạo / gán tài khoản'}</Button>{!user&&<p className="form-hint">Email mới sẽ nhận lời mời. Email đã được tạo trong Auth sẽ được gán vai trò, phòng và nhóm; mật khẩu hiện có không thay đổi.</p>}{user&&<p className="form-hint">Nếu nhân viên còn khách đang phụ trách, hệ thống sẽ không cho đổi Nhóm/Phòng cho tới khi khách được chuyển.</p>}</div></Sheet>
}

export function AdminPage(){const q=useQuery({queryKey:['admin-users'],queryFn:getAdminUsers});const qc=useQueryClient();const[create,setCreate]=useState(false);const[edit,setEdit]=useState<any|null>(null);const[lockBusy,setLockBusy]=useState<string|null>(null);const[lockError,setLockError]=useState('');const lock=async(u:any)=>{setLockBusy(u.id);setLockError('');try{await adminLockUser(u.id,u.status!=='locked');await qc.invalidateQueries({queryKey:['admin-users']})}catch(e){setLockError(e instanceof Error?e.message:'Không thể đổi trạng thái tài khoản')}finally{setLockBusy(null)}};return <div className="page"><PageTitle title="Quản trị hệ thống" subtitle="Tài khoản, vai trò và cơ cấu bán hàng" actions={<Button onClick={()=>setCreate(true)}><Plus className="h-4 w-4" strokeWidth={1.75}/> Tạo tài khoản</Button>}/><div className="admin-summary"><Card><UsersRound className="h-5 w-5" strokeWidth={1.75}/><div><span>Tài khoản</span><strong>{q.data?.length??0}</strong></div></Card><Card><ShieldCheck className="h-5 w-5" strokeWidth={1.75}/><div><span>Đang hoạt động</span><strong>{q.data?.filter((x:any)=>x.status==='active').length??0}</strong></div></Card></div><section><div className="section-title"><h2>Người dùng</h2><span>Admin tạo và khóa tài khoản</span></div>{lockError&&<div className="form-error">{lockError}</div>}{q.isLoading?<Skeleton lines={7}/>:q.isError?<EmptyState title="Không tải được tài khoản" description={q.error.message} action={<Button onClick={()=>q.refetch()}>Thử lại</Button>}/>:q.data?.length?<div className="stack">{q.data.map((u:any)=><Card className="user-row" key={u.id}><div className="avatar soft">{u.full_name?.slice(0,1)??'U'}</div><div className="grow"><strong>{u.full_name||'Chưa có tên'}</strong><span>{roleLabel(u.role)}</span><div className="meta-row"><Badge tone={u.status==='active'?'success':'danger'}>{u.status==='active'?'Đang hoạt động':'Tạm khóa'}</Badge>{u.teams?.name&&<Badge>{u.teams.name}</Badge>}{u.departments?.name&&<Badge>{u.departments.name}</Badge>}</div></div><div className="row-actions"><Button variant="secondary" onClick={()=>setEdit(u)}>Chỉnh</Button><Button variant="ghost" disabled={!!lockBusy} onClick={()=>lock(u)}>{u.status==='active'?<><Lock className="h-4 w-4" strokeWidth={1.75}/> Khóa</>:<><Unlock className="h-4 w-4" strokeWidth={1.75}/> Mở khóa</>}</Button></div></Card>)}</div>:<EmptyState title="Chưa có tài khoản"/>}</section><AdminMasterConfig/><UserForm open={create} onClose={()=>setCreate(false)}/><UserForm open={!!edit} onClose={()=>setEdit(null)} user={edit}/></div>}
