import { useQuery } from '@tanstack/react-query'
import { ArrowLeft, ChevronRight, MessageCircle, Phone, Plus } from 'lucide-react'
import { useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { AddActivitySheet } from '../components/AddActivitySheet'
import { AddContactSheet, NewOpportunitySheet } from '../components/ContactOpportunitySheets'
import { CreateTaskSheet } from '../components/CreateTaskSheet'
import { OpportunityCloseSheet, OpportunityEditSheet, StageSheet } from '../components/OpportunitySheets'
import { QuoteSheet } from '../components/QuoteSheet'
import { TransferCustomerSheet } from '../components/TransferCustomerSheet'
import { useAuth } from '../context/AuthContext'
import { Badge, Button, Card, EmptyState, PageTitle, PriorityBadge, Skeleton } from '../components/UI'
import { getCustomerDetail } from '../lib/api'
import { dateTime, money, potentialLabel, shortMoney } from '../lib/format'

const activityName=(x:string)=>({call:'Gọi điện',message:'Nhắn tin',quote_sent:'Gửi báo giá',lead_created:'Tạo khách',meeting:'Gặp khách',test_drive:'Lái thử',negotiation:'Thương lượng',consultation:'Tư vấn',appointment:'Hẹn gặp',deposit:'Nhận cọc',delivery:'Giao xe',note:'Ghi chú'}[x]??x)
const timelineLabel=(x:string)=>({now:'Ngay',within_7_days:'Trong 7 ngày',within_month:'Trong tháng',one_to_three_months:'1–3 tháng',over_three_months:'Trên 3 tháng',unknown:'Chưa xác định'}[x]??x)
const paymentLabel=(x:string)=>({cash:'Tiền mặt',loan:'Vay ngân hàng',unknown:'Chưa xác định'}[x]??x)

export function CustomerDetailPage(){
  const{profile}=useAuth();
  const{id=''}=useParams();const nav=useNavigate();const[tab,setTab]=useState<'overview'|'activity'|'quotes'>('overview')
  const[activityOpen,setActivityOpen]=useState(false);const[taskOpen,setTaskOpen]=useState(false);const[contactOpen,setContactOpen]=useState(false);const[newOppOpen,setNewOppOpen]=useState(false);const[transferOpen,setTransferOpen]=useState(false);const[editOpen,setEditOpen]=useState(false);const[stageOpen,setStageOpen]=useState(false);const[closeOpen,setCloseOpen]=useState(false);const[quoteOpen,setQuoteOpen]=useState(false)
  const q=useQuery({queryKey:['customer',id],queryFn:()=>getCustomerDetail(id)})
  const c=q.data;const opp=c?.opportunities.find(o=>o.status==='active')??c?.opportunities.find(o=>o.status==='paused')
  if(q.isLoading)return <div className="page"><Skeleton lines={10}/></div>
  if(q.isError)return <div className="page"><EmptyState title="Không tải được hồ sơ khách" description={q.error.message} action={<Button onClick={()=>q.refetch()}>Thử lại</Button>}/></div>
  if(!c)return <div className="page"><EmptyState title="Không tìm thấy khách"/></div>
  const phone=c.contacts.find(x=>x.contact_type==='phone')?.raw_value
  const canEdit=profile?.id===c.owner_user_id
  return <div className="page">
    <button className="back-link" onClick={()=>nav(-1)}><ArrowLeft className="h-4 w-4" strokeWidth={1.75}/> Khách hàng</button>
    <PageTitle title={c.display_name} subtitle={`${c.source_name} · Tạo ${dateTime(c.created_at)}`} actions={<div className="action-row">{phone&&<a className="btn btn-secondary" href={`tel:${phone}`}><Phone className="h-4 w-4" strokeWidth={1.75}/> Gọi</a>}{phone&&<a className="btn btn-secondary" href={`sms:${phone}`}><MessageCircle className="h-4 w-4" strokeWidth={1.75}/> Nhắn</a>}{canEdit&&<Button onClick={()=>setActivityOpen(true)}><Plus className="h-4 w-4" strokeWidth={1.75}/> Tương tác</Button>}{profile&&['team_leader','sales_manager','admin'].includes(profile.role)&&<Button variant="ghost" onClick={()=>setTransferOpen(true)}>Chuyển khách</Button>}</div>}/>
    <div className="tabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>Tổng quan</button><button className={tab==='activity'?'active':''} onClick={()=>setTab('activity')}>Lịch sử</button><button className={tab==='quotes'?'active':''} onClick={()=>setTab('quotes')}>Báo giá</button></div>
    {tab==='overview'&&<div className="detail-grid"><div className="stack">
      <Card><div className="card-head"><h2>Cơ hội đang mở</h2>{opp&&<PriorityBadge value={opp.priority}/>}</div>{opp?<><div className="opp-title"><div><strong>{[opp.product?.name,opp.variant?.name].filter(Boolean).join(' ')||'Chưa xác định xe'}</strong><div className="meta-row"><Badge tone={opp.potential_level==='hot'?'hot':'neutral'}>{potentialLabel(opp.potential_level)}</Badge><button className="badge badge-info clickable" disabled={!canEdit} onClick={()=>setStageOpen(true)}>{opp.stage?.display_name||'Khách mới'}</button>{opp.status==='paused'&&<Badge>Đang tạm hoãn</Badge>}</div></div>{canEdit&&<Button variant="ghost" onClick={()=>setEditOpen(true)}>Chỉnh sửa</Button>}</div>
        <div className="info-rows"><div onClick={()=>canEdit&&setEditOpen(true)}><span>Dự kiến mua</span><strong>{timelineLabel(opp.purchase_timeline)}</strong><ChevronRight className="h-4 w-4" strokeWidth={1.75}/></div><div onClick={()=>canEdit&&setEditOpen(true)}><span>Thanh toán</span><strong>{paymentLabel(opp.payment_type)}{opp.loan_ratio?` ${opp.loan_ratio}%`:''}</strong><ChevronRight className="h-4 w-4" strokeWidth={1.75}/></div><div onClick={()=>canEdit&&setEditOpen(true)}><span>Ngân sách</span><strong>{opp.budget_min||opp.budget_max?`${shortMoney(opp.budget_min)} – ${shortMoney(opp.budget_max)}`:'Chưa có'}</strong><ChevronRight className="h-4 w-4" strokeWidth={1.75}/></div><div onClick={()=>canEdit&&setEditOpen(true)}><span>Đối thủ</span><strong>{opp.competitor_note||'Chưa có'}</strong><ChevronRight className="h-4 w-4" strokeWidth={1.75}/></div></div>
        {canEdit&&<div className="opp-actions"><Button variant="secondary" onClick={()=>setTaskOpen(true)}>Tạo công việc</Button><Button variant="secondary" onClick={()=>setQuoteOpen(true)}>Tạo báo giá</Button><Button variant="ghost" onClick={()=>setCloseOpen(true)}>Trạng thái cơ hội</Button></div>}</>:<EmptyState title="Chưa có cơ hội bán hàng" action={canEdit?<Button onClick={()=>setNewOppOpen(true)}>Tạo cơ hội</Button>:undefined}/>}</Card>
      <Card><h2>Thông tin liên hệ</h2><div className="contact-list">{c.contacts.map(x=><div key={x.id}><span>{x.contact_type}</span><strong>{x.raw_value}</strong></div>)}</div>{canEdit&&<Button variant="ghost" onClick={()=>setContactOpen(true)}><Plus className="h-4 w-4" strokeWidth={1.75}/> Thêm liên hệ</Button>}</Card>
    </div><div className="stack"><Card><div className="card-head"><h2>Việc tiếp theo</h2>{canEdit&&<Button variant="ghost" onClick={()=>setTaskOpen(true)}><Plus className="h-4 w-4" strokeWidth={1.75}/> Thêm</Button>}</div>{c.tasks.filter(t=>t.status==='pending').slice(0,3).map(t=><div className="mini-task" key={t.id}><div><strong>{t.title}</strong><span>{dateTime(t.due_at)}</span></div><PriorityBadge value={t.priority}/></div>)}{!c.tasks.some(t=>t.status==='pending')&&<EmptyState title="Chưa có việc tiếp theo" action={canEdit?<Button variant="secondary" onClick={()=>setTaskOpen(true)}>Tạo công việc</Button>:undefined}/>}</Card><Card><h2>Ghi chú</h2><p className="note-text">{c.note||'Chưa có ghi chú.'}</p></Card></div></div>}
    {tab==='activity'&&<Card><div className="card-head"><h2>Lịch sử tương tác</h2>{canEdit&&<Button variant="secondary" onClick={()=>setActivityOpen(true)}><Plus className="h-4 w-4" strokeWidth={1.75}/> Thêm</Button>}</div><div className="timeline">{c.activities.length?c.activities.map(a=><div className="timeline-item" key={a.id}><div className="timeline-dot"/><div><span>{dateTime(a.occurred_at)}</span><strong>{activityName(a.activity_type)}</strong>{a.note&&<p>{a.note}</p>}</div></div>):<EmptyState title="Chưa có lịch sử tương tác"/>}</div></Card>}
    {tab==='quotes'&&<div className="stack"><div className="section-title"><h2>Báo giá</h2>{opp&&canEdit&&<Button onClick={()=>setQuoteOpen(true)}><Plus className="h-4 w-4" strokeWidth={1.75}/> Báo giá</Button>}</div>{c.quotes.length?c.quotes.map(qt=><Card className="quote-card quote-card-simple" key={qt.id}><div><div className="meta-row"><Badge tone={qt.status==='sent'?'info':qt.status==='accepted'?'success':'neutral'}>{qt.status==='sent'?'Đã gửi':qt.status==='accepted'?'Đã chấp nhận':qt.status==='expired'?'Hết hiệu lực':'Nháp'}</Badge><span>#{String(qt.version).padStart(2,'0')}</span></div><strong className="price">{money(qt.final_price)}</strong><span>{dateTime(qt.sent_at||qt.created_at)}</span>{qt.promotion_note&&<p className="quote-note">{qt.promotion_note}</p>}</div></Card>):<EmptyState title="Chưa có báo giá" action={opp&&canEdit?<Button onClick={()=>setQuoteOpen(true)}><Plus className="h-4 w-4" strokeWidth={1.75}/> Tạo báo giá</Button>:undefined}/>}</div>}
    <TransferCustomerSheet open={transferOpen} onClose={()=>setTransferOpen(false)} customerId={c.id}/><AddContactSheet open={contactOpen} onClose={()=>setContactOpen(false)} customerId={c.id}/><NewOpportunitySheet open={newOppOpen} onClose={()=>setNewOppOpen(false)} customerId={c.id}/><AddActivitySheet open={activityOpen} onClose={()=>setActivityOpen(false)} customerId={c.id} opportunityId={opp?.id}/>
    <CreateTaskSheet open={taskOpen} onClose={()=>setTaskOpen(false)} customerId={c.id} opportunityId={opp?.id}/>
    {opp&&<><OpportunityEditSheet open={editOpen} onClose={()=>setEditOpen(false)} opportunity={opp}/><StageSheet open={stageOpen} onClose={()=>setStageOpen(false)} opportunityId={opp.id} currentStageId={opp.stage?.id}/><OpportunityCloseSheet open={closeOpen} onClose={()=>setCloseOpen(false)} opportunityId={opp.id}/><QuoteSheet open={quoteOpen} onClose={()=>setQuoteOpen(false)} opportunityId={opp.id}/></>}
  </div>
}
